### ISSUE TITLE
Emitter events constants export

### ISSUE THREAD

**Issue by upteran** [jperasmus/stale-while-revalidate-cache#32]
Hi! Thank you for your lib first, great work

I've wanted to use emitter events, like mentioned in README, but realized that `EmitterEvents` constants not exported from index file. And haven't another module in `dist` folder that I can use. Should it be exported from main file, or I missed something ? 

- I've built reproduce with error https://github.com/upteran/test-swr-imports
- version of package: 3.1.2

Tested locally own fix with export, sent PR with it. Added export and types for constants, the simplest fix I think, if you have another solution, I can update it.

**Comment by jperasmus** [comment]
Hi! Thanks for the issue and PR. I will take a look at it.

**Comment by jperasmus** [comment]
You can try your fix out on `v3.1.3` - thanks for the PR!
